### ISSUE TITLE
Problems with running the code

### ISSUE THREAD

**Issue by wernerolaf** [teacherpeterpan/Logic-LLM#5]
Hello, I have troubles with running the code,
First of all I get an errors from unused import. After optimizing imports I get an following error
ModuleNotFoundError: No module named 'func_timeout'

**Comment by wernerolaf** [comment]
set DATASET "Dataset Name [ProntoQA | ProofWriter | FOLIO | LogicalDeduction ｜ AR-LSAT]"
                                       set SPLIT "Dataset Split [dev | test]"
                                       set MODEL "The logic programs are generated by which model? [text-davinci-003 | gpt-4]"
                                       set BACKUP "The random backup answer (random)"

                                       python models/logic_inference.py \
                                               --model_name {$MODEL} \
                                               --dataset_name {$DATASET} \
                                               --split {$SPLIT} \
                                               --backup_strategy {$BACKUP} \
                                               --backup_LLM_result_path ./baselines/results/CoT_{$DATASET}_{$SPLIT}_{$MODEL}.json

**Comment by wernerolaf** [comment]
Traceback (most recent call last):
  File "/home/olafw/Desktop/Logic-LLM/models/logic_inference.py", line 8, in <module>
    from symbolic_solvers.csp_solver.csp_solver import CSP_Program
  File "/home/olafw/Desktop/Logic-LLM/models/symbolic_solvers/csp_solver/csp_solver.py", line 4, in <module>
    import func_timeout
ModuleNotFoundError: No module named 'func_timeout'

**Comment by wernerolaf** [comment]
Now I have an issue with installing pyke

**Comment by wernerolaf** [comment]
Now code runs after additional installs
